name: CI/CD

on:
  push:
    branches:
      - main
      
jobs:
  CI:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install dependencies 📦
        run: yarn install --frozen-lockfile

      - name: Run Tests
        run: yarn test:ci

  CD: 
    name: Continuous Delivery
    runs-on: ubuntu-latest
    needs: CI
    env:
      EAS_TOKEN: ${{ secrets.EAS_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install dependencies 📦
        run: yarn install --frozen-lockfile

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Build Android AAB via EAS 🚀
        run: eas build --platform android --profile production --non-interactive